import logging
import os
import json
import datetime
from pathlib import Path

from dotenv import load_dotenv
from livekit.agents import (
    Agent,
    AgentSession,
    JobContext,
    JobProcess,
    MetricsCollectedEvent,
    RoomInputOptions,
    WorkerOptions,
    cli,
    metrics,
    tokenize,
    function_tool,
    RunContext,
)

from livekit.plugins import (
    murf,
    google,
    deepgram,
    silero,
    noise_cancellation,
)
from livekit.plugins.turn_detector.multilingual import MultilingualModel

logger = logging.getLogger("agent")

load_dotenv(".env.local")


# --------------------------------------------------------------------
# Health & Wellness Companion Persona
# --------------------------------------------------------------------
class Assistant(Agent):
    def __init__(self) -> None:
        super().__init__(
            instructions="""
You are a calm, supportive Health & Wellness voice companion.
You are NOT a doctor or therapist and must not diagnose or give medical advice.

Your job each session:
1) Have a short daily check-in by voice.
2) Ask about:
   - Mood and energy today.
   - Any current stress or worries.
   - 1–3 simple goals or intentions for today.
   - One small self-care action (rest, walk, stretching, hobby, etc.).
3) Offer small, realistic, non-medical suggestions:
   - Break big goals into tiny steps.
   - Suggest short breaks, light movement, or simple grounding ideas.
4) End with a brief recap:
   - Today’s mood.
   - Main 1–3 goals.
   - Planned self-care.
   Then ask: “Does this sound right?”

JSON history:
- At the START of a conversation, you may call get_last_checkin()
  to see the previous entry.
- If there is past data, briefly reference ONE thing, for example:
  “Last time you mentioned feeling low on energy. How does today compare?”

Saving today’s check-in:
- After you have today’s mood, energy, stresses, goals, and self-care,
  create a one-sentence summary of the day in your own words.
- Then call save_checkin(mood, energy, stresses, goals, self_care, summary)
  EXACTLY ONCE per session.
- Do NOT mention files, JSON, or tools to the user.

Safety:
- Stay grounded and encouraging.
- If the user mentions self-harm, wanting to die, or an emergency,
  you must gently encourage them to seek immediate help from local
  emergency services or a trusted professional, and say you’re not
  a substitute for professional care.

Style:
- Short, warm, down-to-earth sentences.
- No emojis or fancy formatting.
"""
        )

    # ----------------------------------------------------------------
    # TOOL: Read last check-in from wellness_log.json
    # ----------------------------------------------------------------
    @function_tool
    async def get_last_checkin(self, context: RunContext):
        """
        Return the most recent check-in from wellness_log.json, if it exists.

        Returns:
            - A dict with the last entry fields, or
            - A string message if no history is available.
        """
        base_dir = Path(__file__).resolve().parent
        log_path = base_dir / "wellness_log.json"

        if not log_path.exists():
            return "No previous check-ins found."

        try:
            with open(log_path, "r", encoding="utf-8") as f:
                data = json.load(f)
        except Exception as e:
            logger.error("Failed to read wellness_log.json: %s", e)
            return "Could not read previous check-ins."

        if not isinstance(data, list) or not data:
            return "No previous check-ins found."

        # Return the last entry
        return data[-1]

    # ----------------------------------------------------------------
    # TOOL: Save today’s check-in to wellness_log.json
    # ----------------------------------------------------------------
    @function_tool
    async def save_checkin(
        self,
        context: RunContext,
        mood: str,
        energy: str,
        stresses: str,
        goals: list[str],
        self_care: str,
        summary: str,
    ):
        """
        Append a new health & wellness check-in entry to wellness_log.json.

        Args:
            mood: User's self-reported mood (free text or scale).
            energy: Description of current energy level.
            stresses: Main stressors or worries today (may be empty).
            goals: List of 1–3 goals or intentions for today.
            self_care: Planned self-care action (rest, walk, hobby, etc.).
            summary: One-sentence recap generated by the agent.

        Behavior:
            - Appends a JSON object to wellness_log.json.
            - Creates the file if it does not exist.
        """
        base_dir = Path(__file__).resolve().parent
        log_path = base_dir / "wellness_log.json"

        entry = {
            "timestamp": datetime.datetime.now().isoformat(timespec="seconds"),
            "mood": mood,
            "energy": energy,
            "stresses": stresses,
            "goals": goals or [],
            "self_care": self_care,
            "agent_summary": summary,
        }

        # Load existing log (if any)
        if log_path.exists():
            try:
                with open(log_path, "r", encoding="utf-8") as f:
                    data = json.load(f)
                if not isinstance(data, list):
                    data = []
            except Exception as e:
                logger.error("Failed to load existing wellness_log.json: %s", e)
                data = []
        else:
            data = []

        data.append(entry)

        try:
            with open(log_path, "w", encoding="utf-8") as f:
                json.dump(data, f, indent=2)
            logger.info("Saved wellness check-in to %s", log_path)
        except Exception as e:
            logger.error("Failed to save wellness_log.json: %s", e)
            return "I tried to save the check-in but ran into a problem."

        # Short confirmation for the model; you still speak your own recap.
        return "Check-in saved successfully."


# --------------------------------------------------------------------
# PREWARM – Silero VAD tuned for softer speech
# --------------------------------------------------------------------
def prewarm(proc: JobProcess):
    proc.userdata["vad"] = silero.VAD.load(
        activation_threshold=0.35,   # more sensitive than default
        min_speech_duration=0.10,    # start speech faster
        min_silence_duration=0.45,   # short pause to end turn
    )


# --------------------------------------------------------------------
# ENTRYPOINT
# --------------------------------------------------------------------
async def entrypoint(ctx: JobContext):
    ctx.log_context_fields = {"room": ctx.room.name}

    session = AgentSession(
        # STT tuned for conversation
        stt=deepgram.STT(
            model="nova-3",
            language="en-US",
            detect_language=False,
            interim_results=True,
            punctuate=True,
            smart_format=True,
        ),

        # LLM (Gemini) for reasoning + tool use
        llm=google.LLM(model="gemini-2.5-flash"),

        # Murf Falcon TTS
        tts=murf.TTS(
            voice="en-US-matthew",
            style="Conversation",
            tokenizer=tokenize.basic.SentenceTokenizer(min_sentence_len=2),
            text_pacing=True,
        ),

        # VAD + turn detection
        vad=ctx.proc.userdata["vad"],
        turn_detection=MultilingualModel(),

        preemptive_generation=True,
    )

    usage_collector = metrics.UsageCollector()

    @session.on("metrics_collected")
    def _on_metrics(ev: MetricsCollectedEvent):
        metrics.log_metrics(ev.metrics)
        usage_collector.collect(ev.metrics)

    async def log_usage():
        logger.info("Usage summary: %s", usage_collector.get_summary())

    ctx.add_shutdown_callback(log_usage)

    await session.start(
        agent=Assistant(),
        room=ctx.room,
        room_input_options=RoomInputOptions(
            noise_cancellation=noise_cancellation.BVC()
        ),
    )

    await ctx.connect()


# --------------------------------------------------------------------
# MAIN
# --------------------------------------------------------------------
if __name__ == "__main__":
    cli.run_app(
        WorkerOptions(
            entrypoint_fnc=entrypoint,
            prewarm_fnc=prewarm,
        )
    )
